version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "UTC"
      time: "00:00"
    allow:
      - dependency-type: "production"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 1
